@startuml
!include <C4/C4_Container>

!include ../include/themes/light.puml

!unquoted procedure Person()
  Person(personAlias, "Main", "CSDIY")
!endfunction

!unquoted procedure BOUNDARY()
  System_Boundary(ms, "cs ") {
    Container(cs, "cs", "Node, Angular", "Does really cool things")
  }
!endfunction

!unquoted procedure EXTSYSTEMS()
  System_Ext(sys_ext1, "必学工具", "1")
  System_Ext(sys_ext2, "好书推荐", "2")
  System_Ext(sys_ext3, "数学基础", "3")
  System_Ext(sys_ext4, "数学进阶", "4")
  System_Ext(sys_ext5, "编程入门", "5")
!endfunction

' Echo the persons
Person()
' The PB system context
BOUNDARY()
' echo the external systems
EXTSYSTEMS()

' Relationships
Rel(personAlias, cs, "CSDIY", "CS")
Rel(cs, sys_ext1, "Must-learn tool", "Tool")
Rel(cs, sys_ext2, "Good book recommendation","Book")
Rel(cs, sys_ext3, "Foundation of mathematics", "Mathematics")
Rel(cs, sys_ext4, "Communicates", "SOAP")
Rel(cs, sys_ext5, "Communicates", "SOAP")

@enduml
