site_name: KM

site_url: https://www.likui.info/wiki/site

theme:
    name: mkdocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - 主页: index.md
    - 开始: getting-started.md
    - 用户手册: 
        - Install: user-guide/installation.md
        - Theme: user-guide/choosing-your-theme.md
        - Customizing: user-guide/customizing-your-theme.md
        - Localizing: user-guide/localizing-your-theme.md
        - Configuration: user-guide/configuration.md
        - Cli: user-guide/cli.md
        - Deploying: user-guide/deploying-your-docs.md
        - Writing: user-guide/writing-your-docs.md
        - README: user-guide/README.md
    - 开发指南: 
        - API: dev-guide/api.md
        - Plugins: dev-guide/plugins.md
        - Themes: dev-guide/themes.md
        - Translations: dev-guide/translations.md
        - README: dev-guide/README.md
    - PPT:
        - ppt: ppt/matlab.md
    - CS:
        - 必学工具: cs/必学工具.md
        - 好书推荐: cs/好书推荐.md
        - 数学基础: cs/数学基础.md
        - 数学进阶: cs/数学进阶.md
        - 编程入门: cs/编程入门.md
        - 电子基础: cs/电子基础.md
    - 阅读:
        - Reading: read/Reading.md
        - Books: read/Books.md
    - 关于:
        - About: about/about.md
       
extra_css:
    - css/extra.css

extra_javascript:
    - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
    - https://unpkg.com/d3@6.7.0/dist/d3.min.js
    - https://unpkg.com/markmap-lib@0.14.1/dist/browser/index.min.js
    - https://unpkg.com/markmap-view@0.14.0/dist/index.min.js
markdown_extensions:
    - toc:
        permalink: 
    - attr_list
    - def_list
    - tables
    - pymdownx.highlight:
        use_pygments: false
    - pymdownx.snippets
    - pymdownx.superfences
    - callouts
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs
    - mkdocs-click
plugins:
  - search
  - blogging:
      dirs: # The directories to be included
        - blog
  - mermaid2:
  - markmap
  - build_plantuml:
        render: 'server' # or "local" for local rendering
        bin_path: '/usr/local/bin/plantuml' # ignored when render: server
        server: 'http://www.plantuml.com/plantuml' # official plantuml server
        disable_ssl_certificate_validation: true # for self-signed and invalid certs
        output_format: 'svg' # or "png"
        diagram_root: 'docs/diagrams' # should reside under docs_dir
        output_folder: 'out'
        input_folder: 'src'
        input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed

copyright: Copyright &copy; 2023 <a href="https://www.mkdocs.org/">MkDocs</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.

