site_name: My Docs

site_url: https://www.likui.info/wiki
nav:
    - Home: index.md
    - About: about.md
theme:
    name: mkdocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django