@startuml
!include <C4/C4_Container>

!include ../include/themes/light.puml

!unquoted procedure Person()
  Person(personAlias, "Main", "CSDIY")
!endfunction

!unquoted procedure BOUNDARY()
  System_Boundary(ms, "cs ") {
    Container(cs, "cs", "Node, Angular", "Does really cool things")
  }
!endfunction

!unquoted procedure EXTSYSTEMS()
  System_Ext(sys_ext1, "必学工具", "Tool")
  System_Ext(sys_ext2, "好书推荐", "Book")
  System_Ext(sys_ext3, "数学基础", "Mathematics")
  System_Ext(sys_ext4, "数学进阶", "Mathematics")
  System_Ext(sys_ext5, "编程入门", "Pogramming")
  System_Ext(sys_ext6, "电子基础", "Electronic basis")
  System_Ext(sys_ext7, "数据结构与算法", "Algorithms")
  System_Ext(sys_ext8, "软件工程", "Software")
  System_Ext(sys_ext9, "体系结构", "Architecture")
  System_Ext(sys_ext10, "操作系统", "System")





!endfunction

' Echo the persons
Person()
' The PB system context
BOUNDARY()
' echo the external systems
EXTSYSTEMS()

' Relationships
Rel(personAlias, cs, "CSDIY", "CS")
Rel(cs, sys_ext1, "Must-learn tool", "Tool")
Rel(cs, sys_ext2, "Good book recommendation","Book")
Rel(cs, sys_ext3, "Foundation of mathematics", "Mathematics")
Rel(cs, sys_ext4, "Mathematical progression", "Mathematical")
Rel(cs, sys_ext5, "Introduction to programming", "Pogramming")
Rel(cs, sys_ext6, "Electronic basis", "Electronic")
Rel(cs, sys_ext7, "Data structures and algorithms", "Algorithms")
Rel(cs, sys_ext8, "Software Engineering", "Software")
Rel(cs, sys_ext9, "Architecture", "Architecture")
Rel(cs, sys_ext10, "Operating system", "System")






@enduml
